//! Native row-level security with the sync driver.

use rupa::core::exec::Executor;
use rupa::core::tx::{Transaction, TxOptions};
use rupa::prelude::*;
use rupa::{SecureTransactional, SecurityContext};
use rupa_driver_postgres::PgExecutor;
use testcontainers_modules::postgres::Postgres;
use testcontainers_modules::testcontainers::runners::SyncRunner;

const DDL: &str = r#"
CREATE SCHEMA rls;
CREATE TABLE rls.docs (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id bigint NOT NULL, title text NOT NULL);
ALTER TABLE rls.docs ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON rls.docs
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
CREATE ROLE app_user NOLOGIN;
GRANT USAGE ON SCHEMA rls TO app_user;
GRANT SELECT, INSERT ON rls.docs TO app_user;
INSERT INTO rls.docs (tenant_id, title) VALUES (1, 'a1'), (2, 'b1');
"#;

#[derive(Debug, Clone, PartialEq, Entity, Insertable)]
#[entity(table = "docs", schema = "rls")]
pub struct Doc {
    #[id]
    id: i64,
    tenant_id: i64,
    title: String,
}

#[test]
fn native_row_level_security_sync() {
    let node = Postgres::default()
        .start()
        .expect("start postgres container");
    let url = format!(
        "postgres://postgres:postgres@{}:{}/postgres",
        node.get_host().unwrap(),
        node.get_host_port_ipv4(5432).unwrap()
    );
    let mut client = postgres::Client::connect(&url, postgres::NoTls).unwrap();
    client.batch_execute(DDL).unwrap();
    let mut db = PgExecutor::new(client);
    let tenant = |id: i64| {
        SecurityContext::new()
            .set("tenant_id", id.to_string())
            .role("app_user")
    };

    let mut tx = db
        .begin_with_security(TxOptions::default(), tenant(1))
        .unwrap();
    let docs = tx.run(select::<Doc>().all()).unwrap();
    assert_eq!(
        docs.iter().map(|d| d.title.as_str()).collect::<Vec<_>>(),
        ["a1"]
    );
    let foreign = Doc {
        id: 10,
        tenant_id: 2,
        title: "x".into(),
    };
    assert!(tx.run(insert::<Doc>().value(&foreign).affected()).is_err());
    tx.rollback().unwrap();

    // Dropped: rolled back on the spot (sync), and the connection is clean.
    drop(
        db.begin_with_security(TxOptions::default(), tenant(2))
            .unwrap(),
    );
    assert!(!db.is_dirty());
    assert_eq!(db.run(select::<Doc>().all()).unwrap().len(), 2);
}
