//! The conformance entities, derived.

use chrono::{DateTime, Utc};
use rupa::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Meta {
    pub score: i64,
    pub flag: bool,
    pub tags: Vec<String>,
    pub nested: Option<Nested>,
    pub note: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Nested {
    pub k: String,
}

/// Scalar, nullable, timestamp and JSON columns; ids chosen by the caller.
#[derive(Debug, Clone, PartialEq, Entity, Gettable, Insertable, Updatable, Deletable)]
#[entity(table = "items", schema = "conformance")]
pub struct Item {
    #[id]
    pub id: i64,
    pub name: String,
    pub label: Option<String>,
    pub qty: i32,
    pub active: bool,
    #[column(name = "created")]
    pub created_at: DateTime<Utc>,
    pub meta: Meta,
    pub extra: Option<Meta>,
}

/// An entity whose id the database generates.
#[derive(Debug, Clone, PartialEq, Entity, Gettable, Insertable, Updatable, Deletable)]
#[entity(table = "notes", schema = "conformance")]
pub struct Note {
    #[id(generated)]
    pub id: i64,
    pub title: String,
    pub body: Option<String>,
    pub pinned: bool,
}

/// Typed insert input for [`Note`]: no id.
#[derive(Debug, Clone, Insertable)]
#[insertable(entity = Note)]
pub struct NewNote {
    pub title: String,
    pub pinned: bool,
}

/// Partial update of one note.
#[derive(Debug, Clone, Updatable)]
#[updatable(entity = Note)]
pub struct NotePatch {
    #[id]
    pub id: i64,
    pub body: Option<Option<String>>,
    pub pinned: Option<bool>,
}

/// Partial update without an id, applied to a filter.
#[derive(Debug, Clone, Updatable)]
#[updatable(entity = Note)]
pub struct SetPinned {
    pub pinned: Option<bool>,
}

/// Postgres schema for the conformance entities. Drops and recreates.
pub const POSTGRES_DDL: &str = r#"
DROP SCHEMA IF EXISTS conformance CASCADE;
CREATE SCHEMA conformance;
CREATE TABLE conformance.items (
    id      bigint PRIMARY KEY,
    name    text NOT NULL,
    label   text,
    qty     integer NOT NULL,
    active  boolean NOT NULL,
    created timestamptz NOT NULL,
    meta    jsonb NOT NULL,
    extra   jsonb
);
CREATE TABLE conformance.notes (
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title   text NOT NULL,
    body    text,
    pinned  boolean NOT NULL
);
"#;

fn at(secs: i64) -> DateTime<Utc> {
    DateTime::from_timestamp(secs, 0).expect("valid timestamp")
}

/// The seed rows every `Item` case starts from.
pub fn items() -> Vec<Item> {
    let meta = |score, flag, tags: &[&str], nested: Option<&str>| Meta {
        score,
        flag,
        tags: tags.iter().map(|t| t.to_string()).collect(),
        nested: nested.map(|k| Nested { k: k.into() }),
        note: None,
    };
    vec![
        Item {
            id: 1,
            name: "apple".into(),
            label: Some("red".into()),
            qty: 3,
            active: true,
            created_at: at(1_700_000_000),
            meta: meta(5, true, &["a", "b"], None),
            extra: None,
        },
        Item {
            id: 2,
            name: "banana".into(),
            label: None,
            qty: 12,
            active: false,
            created_at: at(1_700_000_100),
            meta: meta(7, false, &[], Some("v")),
            extra: Some(meta(1, true, &["x"], None)),
        },
        Item {
            id: 3,
            name: "cherry".into(),
            label: Some("dark_red".into()),
            qty: 7,
            active: true,
            created_at: at(1_700_000_200),
            meta: meta(9, true, &["c"], Some("w")),
            extra: None,
        },
        Item {
            id: 4,
            name: "date".into(),
            label: None,
            qty: 0,
            active: true,
            created_at: at(1_700_000_300),
            meta: meta(-1, false, &[], None),
            extra: None,
        },
    ]
}
