//! Native row-level security on a real Postgres: policies read the context
//! that `begin_with_security` applies inside the transaction.

use rupa::core::exec::AsyncExecutor;
use rupa::core::tx::{AsyncTransaction, AsyncTransactional, TxOptions};
use rupa::prelude::*;
use rupa::{AsyncSecureTransactional, SecurityContext};
use rupa_driver_tokio_postgres::PgExecutor;
use testcontainers_modules::postgres::Postgres;
use testcontainers_modules::testcontainers::runners::AsyncRunner;

/// Policies use `NULLIF(.., '')`: a custom setting set by an earlier
/// (finished) transaction reads back as `''`, not NULL.
const DDL: &str = r#"
DROP SCHEMA IF EXISTS rls CASCADE;
CREATE SCHEMA rls;
CREATE TABLE rls.docs (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL,
    title     text NOT NULL
);
ALTER TABLE rls.docs ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON rls.docs
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);
DO $$ BEGIN CREATE ROLE app_user NOLOGIN; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
GRANT USAGE ON SCHEMA rls TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON rls.docs TO app_user;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA rls TO app_user;
INSERT INTO rls.docs (tenant_id, title) VALUES (1, 'a1'), (1, 'a2'), (2, 'b1');
"#;

#[derive(Debug, Clone, PartialEq, Entity, Insertable)]
#[entity(table = "docs", schema = "rls")]
pub struct Doc {
    #[id(generated)]
    id: i64,
    tenant_id: i64,
    title: String,
}

#[derive(Insertable)]
#[insertable(entity = Doc)]
pub struct NewDoc {
    tenant_id: i64,
    title: String,
}

/// Repositories run unchanged inside a secure transaction.
#[repository]
pub trait Docs {
    #[query(filter = id > $min, order_by = id)]
    async fn after(&mut self, min: i64) -> Result<Vec<Doc>, rupa::DynError>;
}

fn tenant(id: i64) -> SecurityContext {
    SecurityContext::new()
        .set("tenant_id", id.to_string())
        .role("app_user")
}

async fn titles<E: AsyncExecutor>(e: &mut E) -> Vec<String> {
    let docs = e
        .run(select::<Doc>().order_by(col!(Doc::id).asc()).all())
        .await
        .unwrap();
    docs.into_iter().map(|d| d.title).collect()
}

#[tokio::test]
async fn native_row_level_security() {
    let node = Postgres::default()
        .start()
        .await
        .expect("start postgres container");
    let url = format!(
        "postgres://postgres:postgres@{}:{}/postgres",
        node.get_host().await.unwrap(),
        node.get_host_port_ipv4(5432).await.unwrap()
    );
    let (client, connection) = tokio_postgres::connect(&url, tokio_postgres::NoTls)
        .await
        .unwrap();
    tokio::spawn(connection);
    client.batch_execute(DDL).await.unwrap();
    let mut db = PgExecutor::new(client);

    // Each tenant sees only its rows; the context travels with the tx.
    let mut tx = db
        .begin_with_security(TxOptions::default(), tenant(1))
        .await
        .unwrap();
    assert_eq!(tx.context().get("tenant_id"), Some("1"));
    assert_eq!(titles(&mut tx).await, ["a1", "a2"]);
    tx.commit().await.unwrap();
    let mut tx = db
        .begin_with_security(TxOptions::default(), tenant(2))
        .await
        .unwrap();
    assert_eq!(titles(&mut tx).await, ["b1"]);

    // WITH CHECK: writing another tenant's row is refused by the database.
    let foreign = tx
        .run(
            insert::<Doc>()
                .value(&NewDoc {
                    tenant_id: 1,
                    title: "x".into(),
                })
                .affected(),
        )
        .await;
    assert!(
        foreign.is_err(),
        "the policy must reject other tenants' rows"
    );
    tx.rollback().await.unwrap();
    let mut tx = db
        .begin_with_security(TxOptions::default(), tenant(2))
        .await
        .unwrap();
    tx.run(
        insert::<Doc>()
            .value(&NewDoc {
                tenant_id: 2,
                title: "b2".into(),
            })
            .affected(),
    )
    .await
    .unwrap();

    // Savepoints are part of the same transaction: same context.
    let mut inner = tx.begin().await.unwrap();
    assert_eq!(titles(&mut inner).await, ["b1", "b2"]);
    inner.rollback().await.unwrap();

    // Repositories work inside it unchanged.
    let found = Repo::new(&mut tx).after(0).await.unwrap();
    assert_eq!(
        found.iter().map(|d| d.title.as_str()).collect::<Vec<_>>(),
        ["b1", "b2"]
    );
    tx.commit().await.unwrap();

    // Settings are transaction-local: nothing leaks to the next transaction.
    // A role without a tenant sees nothing; the superuser (no context) sees all.
    let mut tx = db
        .begin_with_security(
            TxOptions::default(),
            SecurityContext::new().role("app_user"),
        )
        .await
        .unwrap();
    assert!(
        titles(&mut tx).await.is_empty(),
        "no tenant set: the policy matches nothing"
    );
    tx.commit().await.unwrap();
    assert_eq!(titles(&mut db).await, ["a1", "a2", "b1", "b2"]);

    // A dropped secure transaction rolls back like any other.
    {
        let mut tx = db
            .begin_with_security(TxOptions::default(), tenant(1))
            .await
            .unwrap();
        tx.run(
            insert::<Doc>()
                .value(&NewDoc {
                    tenant_id: 1,
                    title: "gone".into(),
                })
                .affected(),
        )
        .await
        .unwrap();
    }
    assert_eq!(titles(&mut db).await.len(), 4);

    // An invalid key is refused before anything runs.
    let bad = db
        .begin_with_security(
            TxOptions::default(),
            SecurityContext::new().set("Tenant", "1"),
        )
        .await
        .is_err();
    assert!(bad);
    assert_eq!(
        titles(&mut db).await.len(),
        4,
        "the connection is usable afterwards"
    );
}
